# This is a basic workflow to help you get started with Actions

name: My First MuleSoft CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Deploy to Sandbox
        id: deploy-mule-artifacts
        run: |
          # Test the Deployment
          # This is a known issue when using Mule Maven Plugin 3.8.x.
          # mvn clean package install
          # mvn clean deploy -DmuleDeploy
          
          # Deployment using Username & Password
          mvn clean package deploy -DmuleDeploy -DskipTests -s .maven/settings.xml -Danypoint.password=Testing@1234 -Danypoint.username=contentlearning14 -Denv=Sandbox -DbusinessGroup=PantherSchools -DwokerType=MICRO -DworkerSize=1 -Dmule.version=4.4.0 -Dapp.name=faridabaad-meetup-27th-jan
          
          # Deployment using Connected Application
          #mvn clean package deploy -DmuleDeploy -DskipTests -s .maven/settings.xml -Dapp.id=${{ env.CLIENT_ID }} -Dapp.secret=${{ env.CLIENT_SECRET }} -Denv=Sandbox -DbusinessGroup=PantherSchools -DwokerType=MICRO -DworkerSize=1 -Dmule.version=4.4.0 -Dsecure.key=${{env.SECURE_KEY}} -DenvProp=dev
